spring:
  profiles:
    active: dev
  #本服务的名称
  application:
    name: works-service

mybatis-plus:
  type-aliases-package: com.miujike.worksservice.domain
  mapper-locations: classpath:/sqlMappers/*.xml