spring:
  profiles:
    active: dev
  #本服务的名称
  application:
    name: user-service

mybatis-plus:
  type-aliases-package: com.miujike.userservice.domain
  mapper-locations: classpath:/sqlMappers/*.xml