server:
  port: 8791

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://118.25.49.4:8751/eureka/

spring:
#  zipkin:
#    base-url: http://localhost:9411/
#  sleuth:
#    sampler:
#      probability: 1
  datasource:
    url: jdbc:mysql://118.25.49.4:3306/miujike
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #指定从哪个配置中心读取
#  cloud:
#    config:
#      discovery:
#        service-id: config-server
#        enabled: true
#      profile: dev
#      label: master

