spring:
  profiles:
    active: dev
  #本服务的名称
  application:
    name: behavior-service
  jackson:
    time-zone: GMT+8 #处理时区不一致问题

mybatis-plus:
  type-aliases-package: com.miujike.behaviorservice.domain
  mapper-locations: classpath:/sqlMappers/*.xml

fetchNum: 15