spring:
  profiles:
    active: dev
  #本服务的名称
  application:
    name: behavior-service

mybatis-plus:
  type-aliases-package: com.miujike.behaviorservice.domain
  mapper-locations: classpath:/sqlMappers/*.xml
